source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target "detection" do
    pod 'OpenCV', '4.1.0'
    pod 'MNN', '1.0.3'
end
